### ISSUE TITLE
nvm 安装 A4 主题的问题

### ISSUE THREAD

**Issue by shaojunjie0912** [HiNinoJay/hexo-theme-A4#125]
Hi！我的环境是 WSL2-ArchLinux，采用 nvm 管理 node 版本。

![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/96936298/f4e361c4-425b-48e4-8b93-d7a41635bcc3)

按照教程中的安装方法出现了一些问题。具体如下：

我使用 `hexo init Blog` 完成了对 Blog 文件夹的初始化，将 `_config.yml` 文件中 `theme` 修改为 `A4`，采用 `npm install hexo-theme-a4@latest` 安装 A4 主题，添加了 `_config.a4.yml` 文件。

安装完成后使用 `hexo s` 生成网页出错，具体表现为网页空白，且命令行没有正确的输出。

![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/96936298/194241c0-7d15-423f-84d5-953cafd1324c)

![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/96936298/9ceed7cd-2291-4469-b907-3500ea09b64d)

![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/96936298/c4281870-4425-4509-9a8e-72f0ed0275f9)

查看 Blog 文件夹中 node_modules 文件夹中确实安装好了 A4 主题。

![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/96936298/865b8575-5ea7-461a-a198-66bf2559a831)

但貌似 `hexo s` 就是无法正确生成。

此外，当采用默认主题 `theme=landscape` 时可以正常生成网页。

![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/96936298/5f616e09-5c80-4952-93a8-fe6762dbb8da)

并且，当采用 `git clone` 的方式将主题下载到 `themes` 文件夹后，也可以采用 `hexo s` 正常生成。

但不清楚为什么 `npm` 方式会出现问题。请问您有什么建议么？谢谢！

**Comment by HiNinoJay** [comment]
先试着执行`hexo new page index` 生成一个首页

再试着将 _config.yml 文件中 theme 修改为 a4 试试（也就是小写的A4），如果还是不行，试试修改为`hexo-theme-a4`。

应该是npm没找到A4的问题（所以小写试试），如果不是，我就暂时没有头绪了，只能麻烦你采用git的方式安装了

**Comment by shaojunjie0912** [comment]
Hi~

将 _config.yml 文件中 `theme` 从大写的 `A4` 修改为小写的 `a4`，问题解决！
