### ISSUE TITLE
如何調整頁面的寬度以及 字體大小?

### ISSUE THREAD

**Issue by tlyu0419** [HiNinoJay/hexo-theme-A4#137]
我想要增加 預設的頁面寬度 以及 調整字體的大小，
請問應該在哪個地方調整設定呢? 謝謝!

**Comment by tlyu0419** [comment]
我翻到對應的程式碼了，提供其他人參考
調整頁面寬度要修改 public/css/style.css 中 .index-main 段落的 max-width 設定
調整字體大小要修改 public/css/style.css 中 body 段落的 font-size 設定

**Comment by HiNinoJay** [comment]
最新版本的A4已经向用户提供配置：自由调整网页宽度大小
