### ISSUE TITLE
文章换行异常

### ISSUE THREAD

**Issue by baoduoxu** [HiNinoJay/hexo-theme-A4#144]
下图是本地部署之后的效果：

![image](https://github.com/user-attachments/assets/162265c3-b223-4f3b-ad5b-6d24c5514afd)

下图是本地 vscode 预览的效果：

![image](https://github.com/user-attachments/assets/de7d4356-8673-4bb0-b87f-96a36931c7de)

几乎每篇文章以及主页都有这种现象。

**Comment by HiNinoJay** [comment]
看起来像是一遇到公式解析就会换行，能麻烦你发一份md文件到我的邮箱吗，我复现一下：welcome@ninojay.top
