### ISSUE TITLE
请问本地服务器显示正常，推送到github上部署后网页什么都不显示是什么问题

### ISSUE THREAD

**Issue by Rookie-Sensen** [HiNinoJay/hexo-theme-A4#30]
我用hexo s命令在本地打开是正常显示的，但是push到github上之后，用netlify也部署成功了，但是打开网站是一片空白，什么都不显示，是哪里的问题呢。

**Comment by HiNinoJay** [comment]
加我微信 why-not-have-a-drink，更方便解决
