### ISSUE TITLE
关于hexo-reference中引用的hint.min.css问题

### ISSUE THREAD

**Issue by AllenGo912** [HiNinoJay/hexo-theme-A4#31]
最近发现页面加载很慢，经过排查是hint.min.css的请求速度很慢，发现该CDN: https://cdn.jsdelivr.net/hint.css/2.4.1/hint.min.css, 速度很慢，找到hexo-reference的原作者，发现已经在5年前就停更了，因此我fork了hexo-reference的代码，并修改了新版本的CDN，速度很快。

可直接  `npm install hexo-reference-new --save` 安装新插件

npmjs地址：https://www.npmjs.com/package/hexo-reference-new
github地址：https://github.com/AllenGo912/hexo-reference-new

**旧：**
![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/66147869/e95ec150-5d22-40d3-80ff-4cc7d77f7284)
![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/66147869/8d109cd2-b611-4bb0-8912-94b0ea5b371e)

**新：**
![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/66147869/d6501d49-1f92-4c27-a181-a6a9f623837c)
![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/66147869/c633b7bd-9676-4672-b2c9-b1f501952cd2)

**Comment by HiNinoJay** [comment]
感谢支持A4，已更新说明  A4支持hexo-reference的相关博文
https://ninojay.top/hexoplugin/hexo-reference/#%E5%85%B6%E4%BB%96
