### ISSUE TITLE
可以加个友链页面

### ISSUE THREAD

**Issue by xiaohao8** [HiNinoJay/hexo-theme-A4#37]
如题

**Comment by HiNinoJay** [comment]
用户可以自己创建一个 page，然后把地址放到页底的链接栏，也可以放在开头的链接栏。如果是特意设计一个友联界面，我觉得违反了A4追求的简洁性。我的友链界面示例：https://ninojay.top/friends/

**Comment by xiaohao8** [comment]
哦，谢谢！
