### ISSUE TITLE
关于首页的标题能否设置大小

### ISSUE THREAD

**Issue by seongnoe** [HiNinoJay/hexo-theme-A4#44]
**您好，目前展示首页如果设置中文title，好像字体样式挺大的，能否进行修改呢？**

**Comment by HiNinoJay** [comment]
您好，可以修改。

如果你通过git方式安装，可以先关闭A4的CDN，随后找到style.css文件，找到.index-logo，修改其中的font-size参数值即可。

因为你是第一个提出这个问题的人，如果提出这样需求的人足够多，那么我可以在随后版本的配置文件中加一个配置供用户调整～

**Comment by seongnoe** [comment]
收到，感谢您的解答！
