### ISSUE TITLE
字体更换问题

### ISSUE THREAD

**Issue by jiangjiang1116** [HiNinoJay/hexo-theme-A4#48]
pc端能正确显示，但移动端不能，比如我引入了楷体的ttf，然后配置好之后在pc上正确显示，手机上不能。

**Comment by jiangjiang1116** [comment]
手机：![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/48378932/916e0337-daa1-4412-9065-4202d9815e24)
PC：![1694510759051](https://github.com/HiNinoJay/hexo-theme-A4/assets/48378932/351d2795-a2fd-4b2a-8a66-2a4c033b6dae)

**Comment by HiNinoJay** [comment]
老问题，字体自选暂不支持，希望大佬出手填补A4这一空白。我目前暂无想法。

**Comment by havenoideawhatismyname** [comment]
今天试出来了一个简单的办法，目前看上去效果还不错，尚且不知道有什么瑕疵，个人用的字体是思源宋体。
第一步：先在A4的_config.yml里面把cdn关掉。
第二步：打开fonts.css文件，直接在网页的F12里面写也可以：
`@font-face {
  font-family:montserrat;
  font-style:normal;
  font-weight:400;
  src:local(""),
  url(../fonts/montserrat-v23-latin-600.woff2) format("woff2"),
  url(../fonts/montserrat-v23-latin-600.woff) format("woff")
}`
`font-family`改成字体名称，下面两个不同格式的url分别贴上两个字体文件的下载链接，也可以再加一个oppentype的，ttf我没试过。
也可以把上面的local后面改成文件的位置。
第三步：打开style.css文件，找到body的这一段：
`body
{
    /* font-family: "Montserrat", "SF UI Text", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Segoe UI", "Helvetica Neue", Helvetica, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif; */
    font-family: <字体名称>;
    font-size: 16px;
    line-height: 1.75;
    letter-spacing: 0.6px;
    color: var(--font-color-1);
    background: #efeaf2;
}`
（我有自定义背景色所以可能不一样）
把`font-family`后面改成刚刚写在fonts文件里的字体名称，然后保存。
第四步：运行 hexo clean && hexo g && hexo s看效果，需要一点时间才能加载出来。
我自己试了下手机端谷歌和电脑端火狐都效果不错，edge响应时间比较长但加载好之后效果也挺好的，safari貌似适用不了。

**Comment by HiNinoJay** [comment]
2023-11-23
已经更换 默认字体为  notoserifsc 字体，个人觉得挺漂亮。当然思源宋体也可支持，看大家的反馈，如果大家都喜欢思源宋体的话，后期可把默认字体换成思源宋体。

至于更换其他字体，后期应该会开发一个新版本，或者写一篇教程，提供让用户自己更换字体的方法。
