### ISSUE TITLE
feature：“首页”，“文章”，“关于” 这几个栏目的名称能否支持修改

### ISSUE THREAD

**Issue by tobenot** [HiNinoJay/hexo-theme-A4#54]
比如想改成其他的名称，“手稿”、“作者”这种
目前修改会出现异常的表现：
![image](https://github.com/HiNinoJay/hexo-theme-A4/assets/42083410/27d2eb2d-902a-4bb9-ae9c-996c442d9803)

**Comment by HiNinoJay** [comment]
请先更新v1.7.3，不更新的话，只能修改'文章'，无法修改'首页'。

因为 最终 页面的生成 会取 _config.a4.yml 和 _config.yml 的并集
所以当你复制了一份该配置文件为 _config.a4.yml后，强烈建议你将 _config.yml 中的 menu,showInMenu中的配置都 注释掉
甚至可以注释掉 _config.yml中所有的配置，这样最终只会基于你的 _config.a4.yml

**Comment by tobenot** [comment]
备忘：这里说的_config.yml，主题文件里面有一个
![$VWPVZ$ T6A85@OB1R}U`7C](https://github.com/HiNinoJay/hexo-theme-A4/assets/42083410/d99329d5-a0e6-4ecc-b503-824165a3aed6)
