### ISSUE TITLE
Customized favicon 404 on Non-index pages -- Possible cause & Possible fix

### ISSUE THREAD

**Issue by Tonkovski** [HiNinoJay/hexo-theme-A4#96]
Thanks for spending time viewing this issue, and hope this will be of some help.

After changing `favicon` in `_config.a4.yml` the theme will be unable to locate exact location of modified favicon path.

E.g. If the config is modified as follows:
```yml
# 相对于source目录下的头像url
favicon: /img/favicon.jpeg
```
This is what the page looks like:
<img width="881" alt="ScreenCapture" src="https://github.com/HiNinoJay/hexo-theme-A4/assets/44365191/ea9d0097-5262-4761-bf8a-21e89f1091e2">

The issue is possibly caused by codes in `/blob/main/layout/_partial/post-header.ejs` where the avatar is defined as follows:
```ejs
    <div class="header-container">
        <img style="
        width: 56px;
        height: auto;" alt="^-^" cache-control="max-age=86400" class="header-img" src="<%- url_for('/img/favicon.webp') %>" width="10%"></img>
        <div class="header-content">
            <a class="logo" href="<%- url_for() %>"><%= config.title %></a> 
            <span class="description"><%= config.description %></span> 
        </div>
        
    </div>
```

Changing `url_for('/img/favicon.webp')` into `url_for(theme.favicon)` fixes this issue.
<img width="882" alt="capt2" src="https://github.com/HiNinoJay/hexo-theme-A4/assets/44365191/8a87f162-b309-4801-a5b6-84a0ed6c0704">

**Comment by HiNinoJay** [comment]
nice issue, thanks a lot.🍺

The problem has been fixed.

If you are using git installation, you can pull down the code again. 
If you use npm, it will be updated in the next version
